version: '3'
services:
  app:
    restart: always
    links:
    - db
    build: .
    ports:
      - 5001:5001
    volumes:
      - .:/app
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_acl_service
    volumes:
      - ./postgres-data/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
