version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    env_file:
      - dev.env
      - secrets/aws.env
    environment:
      - PYTHONUNBUFFERED=0  # Causes print statements to be logged
    
networks:
  default:
    external:
      name: record_service_default