version: '3'
services:
  app:
    restart: always
    links:
    - db
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - dev.env
      - secrets/aws.env
    environment:
      - PYTHONUNBUFFERED=0  # Causes print statements to be logged

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_record_service
    volumes:
      - ./postgres-data/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  ipfs:
    restart: always
    image: jbenet/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
