version: "3.0"
services:
  record_service:
    ports:
      - "5000:5000"
    env_file:
      - record_service.env
      - secrets/record_service_secrets.env
    environment:
      - PYTHONUNBUFFERED=0 # Causes print statements to be logged
    image: "361641763854.dkr.ecr.us-east-1.amazonaws.com/record_service:latest"
    logging:
      driver: awslogs
      options:
        awslogs-group: medfs
        awslogs-region: us-east-1
        awslogs-stream-prefix: record_service

  ipfs:
    image: jbenet/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: mefs
        awslogs-region: us-east-1
        awslogs-stream-prefix: ipfs

  acl_service:
    ports:
      - "5002:5002"
    env_file:
      - acl_service.env
      - secrets/acl_service_secrets.env
    environment:
      - PYTHONUNBUFFERED=0 # Causes print statements to be logged
    image: "361641763854.dkr.ecr.us-east-1.amazonaws.com/acl_service:latest"
    logging:
      driver: awslogs
      options:
        awslogs-group: medfs
        awslogs-region: us-east-1
        awslogs-stream-prefix: acl_service
