version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 2GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0657624c"
        - "subnet-116e084d"
      security_groups:
        - "sg-0462beb4cc5304c2d" 
      assign_public_ip: ENABLED
