export const ERR_NOT_AUTHORIZED = "NOT_AUTHORIZED";
export const ERR_NOT_LOGGED_IN = "NOT_LOGGED_IN";
export const ERR_UNKNOWN = "UNKNOWN_ERROR";
export const ERR_USER_NOT_FOUND = "USER_NOT_FOUND";
export const ERR_NO_PERM_FOR_RECORD = "NO_PERMISSION_FOR_RECORD";
